### ISSUE TITLE
Support input filenames/filepaths longer than 30 characters

### ISSUE THREAD

**Issue by devenbansod** [alexorso/tslgenerator#4]
Hi,

I see that for [Mac OSX](https://github.com/alexorso/tslgenerator/blob/5b7a3377ed79fba1360c6fdec92a5a39f860c412/MacOSX/main.c#L48) implementation, it uses dynamic allocation of memory for storing the output file name (which is set based on value of the `input_file` [here](https://github.com/alexorso/tslgenerator/blob/5b7a3377ed79fba1360c6fdec92a5a39f860c412/MacOSX/main.c#L86)).

But for similar instances in [Linux](https://github.com/alexorso/tslgenerator/blob/5b7a3377ed79fba1360c6fdec92a5a39f860c412/Linux/main.c#L48), [Win32](https://github.com/alexorso/tslgenerator/blob/5b7a3377ed79fba1360c6fdec92a5a39f860c412/Win32/main.c#L48) and [Win8](https://github.com/alexorso/tslgenerator/blob/5b7a3377ed79fba1360c6fdec92a5a39f860c412/Win8/main.c#L48), it uses a constant limit of 30 characters which might overflow in case of longer filenames or filepaths.

If you think this is a valid bug, I could go ahead and make a PR to fix this.

**Comment by alexorso** [comment]
Yes, it is. In fact, I thought this had been fixed before, but apparently, that's not the case. 

Please feel free to make a PR for it.

Thanks!

**Comment by amirbehzad** [comment]
I remember I only fixed this for OSX.

**Comment by devenbansod** [comment]
I added a PR at #5
